   export const API_BASE_URL = 'http://192.168.1.170:8080/';  //192.168.1.170
   export const GET_EMPLOYEE = 'GET_EMPLOYEE'
   export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
   export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
   export const DELETE_EMPLOYEE =  'DELETE_EMPLOYEE'
   export const SEARCH_EMPLOYEE =  'SEARCH_EMPLOYEE'
   export const FETCH_EMPLOYEE_SUCCESS ='FETCH_EMPLOYEE_SUCCESS'
