export default{
    GET_EMPLOYEE : 'GET_EMPLOYEE',
    EDIT_EMPLOYEE :'EDIT_EMPLOYEE',
    ADD_EMPLOYEE:'ADD_EMPLOYEE',
    DELETE_EMPLOYEE : 'DELETE_EMPLOYEE',
    SEARCH_EMPLOYEE : 'SEARCH_EMPLOYEE',
}